# Generated by Django 3.0.5 on 2020-05-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dif_easy', models.IntegerField()),
                ('dif_med', models.IntegerField()),
                ('dif_hard', models.IntegerField()),
                ('data_score', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AuthUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_id', models.IntegerField()),
                ('data_add', models.DateTimeField(auto_now_add=True)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AuthUser')),
            ],
        ),
    ]
